platform: avr
cpu: atmega328p
frequencies:
  cpu_freq: 16000000
memory:
  flash: 32768
  ram: 2048
pins:
  led:
    port: 0
    pin: 5
    mode: output
  uart_tx:
    port: 2
    pin: 1
    mode: alt_function
  uart_rx:
    port: 2
    pin: 0
    mode: alt_function
