platform: esp32
cpu: xtensa-lx6
frequencies:
  apb_freq: 80000000
  cpu_freq: 240000000
memory:
  flash: 4194304    # 4MB
  ram: 524288       # 512KB
features:
  enable_log: true
  enable_cli: false
  enable_ota: false